services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=app-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.metrics.address=:8080"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sigcratotumo@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
      
      # CORS Middleware (if needed)
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://${DOMAIN}"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "com.metamag.project=sig-platform"

  api-laravel:
    image: lcrojano1/api-laravel-cra:latest
    env_file: ./apps/api-laravel/.env
    #user: "33:999"
    volumes:
      - api-laravel-vendor:/var/www/html/vendor
      - ./tools/docker/php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./tools/docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf
      - ./apps/tileserver-gl:/data
      - composer-cache:/root/.composer/cache
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
   
    restart: unless-stopped
    labels:
      - "com.metamag.project=sig-platform"

  api-laravel-nginx:
    image: nginx:alpine
    volumes:
      - ./tools/docker/nginx/api.custom.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 128m
    depends_on:
      - api-laravel
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-laravel.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.api-laravel.entrypoints=websecure"
      - "traefik.http.routers.api-laravel.tls.certresolver=myresolver"
      - "traefik.http.services.api-laravel.loadbalancer.server.port=80"
      - "traefik.docker.network=app-network"
      # ✅ Apply CORS middleware to this service
      - "traefik.http.routers.api-laravel.middlewares=cors@docker"
      # ✅ Extra router for /config.json on main domain
      #- "traefik.http.routers.configjson.rule=Host(`${DOMAIN}`) && Path(`/config.json`)"
      - "traefik.http.routers.configjson.entrypoints=websecure"
      - "traefik.http.routers.configjson.tls.certresolver=myresolver"
      - "traefik.http.services.configjson.loadbalancer.server.port=80"
      - "traefik.http.routers.configjson.middlewares=cors@docker"
      - "com.metamag.project=sig-platform"

  client-ui-nginx:
    image: lcrojano1/nginx-client-ui-cra:latest
    volumes:
      - ./tools/docker/nginx/client.custom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/client-ui/src/assets/app.config.json:/usr/share/nginx/html/assets/app.config.json
    networks:
      - app-network
    depends_on:
      - api-laravel
      - tileserver
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-ui.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.client-ui.entrypoints=websecure"
      - "traefik.http.routers.client-ui.tls.certresolver=myresolver"
      - "traefik.http.services.client-ui.loadbalancer.server.port=80"
      - "traefik.docker.network=app-network"
      - "com.metamag.project=sig-platform"
  
  tileserver:
    image: lcrojano1/tileserver-gl-cra:latest
    volumes:
       - tileserver_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tileserver.rule=Host(`tiles.${DOMAIN}`)"
      - "traefik.http.routers.tileserver.entrypoints=websecure"
      - "traefik.http.routers.tileserver.tls.certresolver=myresolver"
      - "traefik.http.services.tileserver.loadbalancer.server.port=80"
      - "traefik.docker.network=app-network"
      - "com.metamag.project=sig-platform"




networks:
  app-network:
    driver: bridge
    name: app-network
    labels:
        - "com.metamag.project=sig-platform"

volumes:
  api-laravel-vendor:
  composer-cache:
  client-ui-node-modules:
  client-ui-pnpm-store:
  client-ui-cache:
  tileserver_data:
