FROM nginx:alpine

# Clean default NGINX html
RUN rm -rf /usr/share/nginx/html/*

# Copy built Angular app from builder stage
COPY ./dist/browser/* /usr/share/nginx/html

# Copy custom NGINX config 
COPY ./docker/nginx/nginx.default.conf /etc/nginx/conf.d/default.conf

# Good practice for security: drop root
#USER nginx

# Expose default HTTP port
EXPOSE 80

# Start nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
